
package day1_service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* Web_ServiceService service = new Web_ServiceService();
* WebService portType = service.getWebServicePort();
* portType.get(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "Web_ServiceService", targetNamespace = "http://day1_service/", wsdlLocation = "http://localhost:9001/Service/hello?wsdl")
public class WebServiceService extends Service {

	private final static URL WEBSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(day1_service.WebServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = day1_service.WebServiceService.class.getResource(".");
			url = new URL(baseUrl, "http://localhost:9001/Service/hello?wsdl");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'http://localhost:9001/Service/hello?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		WEBSERVICESERVICE_WSDL_LOCATION = url;
	}

	public WebServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public WebServiceService() {
		super(WEBSERVICESERVICE_WSDL_LOCATION, new QName("http://day1_service/", "Web_ServiceService"));
	}

	/**
	 * 
	 * @return returns WebService
	 */
	@WebEndpoint(name = "Web_ServicePort")
	public WebService getWebServicePort() {
		return super.getPort(new QName("http://day1_service/", "Web_ServicePort"), WebService.class);
	}

}
