
package day1_service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@javax.jws.WebService(name = "Web_Service", targetNamespace = "http://day1_service/")
public interface WebService {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "get", targetNamespace = "http://day1_service/", className = "day1_service.Get")
	@ResponseWrapper(localName = "getResponse", targetNamespace = "http://day1_service/", className = "day1_service.GetResponse")
	public String get(@WebParam(name = "arg0", targetNamespace = "") String arg0);

}
